version: '3.8'
services:
  landing_service:
    image: landing_service:dev
    container_name: landing_service
    ports:
      - "8080:8080"
  login_service:
    image: login_service:dev
    container_name: login_service
    ports:
      - "30100:30100"
  apiGW_service:
    image: apiGW_service:dev
    container_name: apiGW_service
    ports:
      - "30200:30200"

