version: "3"
services:
  landing-service:
    image: scottkurt/gallery:landing-service_dev_
    container_name: landing-service
    entrypoint: ["go","run","."]
    depends_on:
      - apigw-service
    environment:
      - API_SERVER=apigw-service
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./landing_service/
        target: /app
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 500M
        reservations:
          cpus: 0.5
          memory: 500M
  login-service:
    image: scottkurt/gallery:login-service_dev_
    container_name: login-service
    ports:
      - "30100:30100"
    volumes:
      - type: bind
        source: ./login_service
        target: /app
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 500M
        reservations:
          cpus: 0.5
          memory: 500M
  apigw-service:
    image: scottkurt/gallery:apigw-service_dev_
    container_name: apigw-service
    entrypoint: ["go","run","."]
    environment:
      - LOGIN_SERVER=login-service
      - NOTES_SERVER=notes-service
    depends_on:
      - login-service
    ports:
      - "30200:30200"
    volumes:
      - type: bind
        source: ./apigw_service
        target: /app
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 500M
        reservations:
          cpus: 0.5
          memory: 500M        

  notes-service:
    image: scottkurt/gallery:notes-service_dev_
    container_name: notes-service
    ports:
      - "30300:30300"
    volumes:
      - type: bind
        source: ./notes_service
        target: /app
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 500M
        reservations:
          cpus: 0.3
          memory: 500M

