version: "3"
services:
  landing-service:
    image: "{{ .Values.IMAGE_TAG_LANDING_SERVICE }}"
    container_name: landing-service
    environment:
      - API_SERVER=apigw-service
    ports:
      - "8080:8080"

  login-service:
    image: "{{ .Values.IMAGE_TAG_LANDING_SERVICE }}"
    container_name: login-service
    ports:
      - "30100:30100"
  apigw-service:
    image: "{{ .Values.IMAGE_TAG_LANDING_SERVICE }}"
    container_name: apigw-service
    environment:
      - LOGIN_SERVER=login-service
      - NOTES_SERVER=notes-service
    ports:
      - "30200:30200"
  notes-service:
    image: "{{ .Values.IMAGE_TAG_LANDING_SERVICE }}"
    container_name: notes-service
    ports:
      - "30300:30300"



