version: "3"
services:
  landing-service:
    image: "{{ .Values.IMAGE_TAG_LANDING_SERVICE }}"
    container_name: landing-service
    entrypoint: ["go","run","."]
    environment:
      - API_SERVER=apigw-service
    ports:
      - "8080:8080"
    labels:
      kompose.service.type: nodeport
      kompose.service.nodeport.port: "30500"
      kompose.image-pull-secret: "regcred"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 500M
        reservations:
          cpus: '1'
          memory: 200M
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

  login-service:
    image: "{{ .Values.IMAGE_TAG_LOGIN_SERVICE }}"
    container_name: login-service
    entrypoint: ["go","run","."]
    ports:
      - "30100:30100"
    labels:
      kompose.image-pull-secret: "regcred"
  apigw-service:
    image: "{{ .Values.IMAGE_TAG_APIGW_SERVICE }}"
    container_name: apigw-service
    entrypoint: ["go","run","."]
    environment:
      - LOGIN_SERVER=login-service
      - NOTES_SERVER=notes-service
    ports:
      - "30200:30200"
    labels:
      kompose.image-pull-secret: "regcred"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 500M
        reservations:
          cpus: '1'
          memory: 200M
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

  notes-service:
    image: "{{ .Values.IMAGE_TAG_NOTES_SERVICE }}"
    container_name: notes-service
    entrypoint: ["go","run","."]
    ports:
      - "30300:30300"
    labels:
      kompose.image-pull-secret: "regcred"



