apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yaml -o gallery_chart/templates/
    kompose.image-pull-secret: regcred
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: apigw-service
  name: apigw-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigw-service
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yaml -o gallery_chart/templates/
        kompose.image-pull-secret: regcred
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/k8-default: "true"
        io.kompose.service: apigw-service
    spec:
      containers:
        - env:
            - name: LOGIN_SERVER
              value: login-service
            - name: NOTES_SERVER
              value: notes-service
          image: '{{ .Values.IMAGE_TAG_APIGW_SERVICE }}'
          name: apigw-service
          ports:
            - containerPort: 30200
              hostPort: 30200
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: "1048576e3"
            requests:
              memory: "52428800"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
