apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apigw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigw-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: landingservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: landing-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95